s="Tops Technologies"

print(s)
print("Length Of String : ",len(s))
print(s.capitalize())
print(s.casefold())
print(s.center(40,"&"))
print(s.count("o"))
print(s.endswith("es3"))
print(s.find("log"))
print(s.index("T",2))
print("tops123".isalnum())
print("123".isalnum())
print("tops".isalnum())
print("tops 123".isalnum())
print("123".isnumeric())
print("tops".isalpha())
print(s.istitle())
print(" ".isspace())
print(s.upper())
print(s.lower())
print(s.swapcase())
